Make OPTIONAL default and allowed value of mutual_authentication
Before this change Kerberos authentication worked only if
Kerberos option mutual_authentication was explicitly set to DISABLED.
OPTIONAL was not default value anymore but it wasn't among allowed
values of mutual_authentication. Therefore these authentications failed
with raised exception:

    ValueError: Unknown value for mutual_authentication

Relates: #424
Relates: #472